version: '3'

services:
  wildfly:
    image: api-order
    ports:
      - "8881:8080"
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
